server:
  port: 8002
mybatis:
  type-aliases-package: com.ldw.microservice.entity
  mapper-locations: mybatis/mapper/**/*.xml
spring:
  application:
    name: microservice-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.172.129:8848
        prefer-ip-address: true  # 让 Feign 解析为 IP 地址
        namespace: dev  # 或者具体的 namespace ID
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
# 日志配置文件
logging:
  config: classpath:logback-spring.xml